version: "3.8"

services:

  mongo:
    image: mongo:4.4
    container_name: mytrip-mongo
    restart: always
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: mytrip-backend
    restart: always
    networks:
      - proxy
      - internal
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${MONGO_JWT_SECRET}
      CLOUDINARY_CLOUD: ${CLOUDINARY_CLOUD}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: mytrip-frontend
    restart: always
    networks:
      - proxy
      - internal
    depends_on:
      - backend

volumes:
  mytrip_mongo_data:
    external: true
networks:
  proxy:
    external: true
  internal:
    external: true
