apiVersion: apps/v1
kind: Deployment
metadata: { name: mytrip-frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: mytrip-frontend } }
  template:
    metadata: { labels: { app: mytrip-frontend } }
    spec:
      containers:
        - name: frontend
          image: mytrip-frontend:latest
          imagePullPolicy: Never
          ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata: { name: mytrip-frontend }
spec:
  selector: { app: mytrip-frontend }
  ports:
    - port: 80
      targetPort: 80
  type: NodePort