apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector: { matchLabels: { app: mongo } }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports: [{ containerPort: 27017 }]
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: sergio
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: sergio
      volumes:
        - name: mongo-data
          emptyDir: {}
      

---
apiVersion: v1
kind: Service
metadata: { name: mongo }
spec:
  selector: { app: mongo }
  ports:
    - port: 27017
      targetPort: 27017